
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class ChangePassword extends javax.swing.JFrame {
    Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Rohan\\Documents\\NetBeansProjects\\OOP_Project\\bg1.jpg");
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        this.setContentPane(new JPanel()
                {
                    @Override
                    public void paintComponent(Graphics g)
                {
                    super.paintComponent(g);
                    g.drawImage(img, 0, 0, 710, 590, this);
                }
                });
        setResizable(false);
       
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pass_user = new javax.swing.JLabel();
        pass_phone = new javax.swing.JLabel();
        pass_new = new javax.swing.JLabel();
        pass_confirm = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        in_pass = new javax.swing.JPasswordField();
        in_confirm = new javax.swing.JPasswordField();
        in_user = new javax.swing.JTextField();
        in_phone = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Change Password");

        pass_user.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pass_user.setText("Username:");

        pass_phone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pass_phone.setText("Phone Number:");

        pass_new.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pass_new.setText("New Password: ");

        pass_confirm.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pass_confirm.setText("Confirm New Password:");

        jButton1.setText("Reset Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        in_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_passActionPerformed(evt);
            }
        });

        in_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_confirmActionPerformed(evt);
            }
        });

        in_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_userActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pass_new, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pass_phone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pass_user)
                                    .addGap(165, 165, 165)))
                            .addComponent(pass_confirm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_pass)
                            .addComponent(in_confirm)
                            .addComponent(in_user)
                            .addComponent(in_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(237, 237, 237))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_user)
                    .addComponent(in_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_phone)
                    .addComponent(in_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_new)
                    .addComponent(in_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_confirm)
                    .addComponent(in_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cancel))
                .addGap(77, 77, 77))
        );

        setVisible(false);
        setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (in_user.getText().equals("") || in_phone.getText().equals("") || in_pass.getText().equals("") || in_confirm.getText().equals("") )
             {
            JOptionPane.showMessageDialog(null,"Please enter all the details");
        }
        else {
            
            String name = in_user.getText();
            String phone_number = in_phone.getText();
            String password = in_pass.getText();
            String final_pass = in_confirm.getText();     
            
            //accessing user database
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myConnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user?characterEncoding=latin1","root","root");
                Statement mySttmt = myConnn.createStatement();
                ResultSet mytRs = mySttmt.executeQuery("select * from userdata where id= '"+name+"'" );
                if(mytRs.next())
                {
                    if(mytRs.getString("phone").equals(phone_number))
                    {
                        if(password.equals(final_pass))
                        {
                            Statement myStmt = myConnn.createStatement();
                            myStmt.executeUpdate("update userdata set password ='"+password+"' where id='"+name+"'");
                            dispose();
                            Login log = new Login();
                            log.setVisible(true);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"The passwords do not match");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"User details do not match");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"There is no such user");
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void in_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_passActionPerformed

    private void in_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_confirmActionPerformed

    private void in_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_userActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField in_confirm;
    private javax.swing.JPasswordField in_pass;
    private javax.swing.JTextField in_phone;
    private javax.swing.JTextField in_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pass_confirm;
    private javax.swing.JLabel pass_new;
    private javax.swing.JLabel pass_phone;
    private javax.swing.JLabel pass_user;
    // End of variables declaration//GEN-END:variables
}
