/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author rushi
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    
    Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Rohan\\Documents\\NetBeansProjects\\OOP_Project\\bg1.jpg");
    public CreateAccount() {
        this.setContentPane(new JPanel()
                {
                    @Override
                    public void paintComponent(Graphics g)
                {
                    super.paintComponent(g);
                    g.drawImage(img, 0, 0, 700, 560, this);
                }
                });
        setResizable(false);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_account_label = new javax.swing.JLabel();
        set_emailid_label = new javax.swing.JLabel();
        set_username_label = new javax.swing.JLabel();
        set_password_label = new javax.swing.JLabel();
        set_phone_number_label = new javax.swing.JLabel();
        set_emailid_field = new javax.swing.JFormattedTextField();
        set_username_field = new javax.swing.JTextField();
        set_password_field = new javax.swing.JPasswordField();
        set_phone_number_field = new javax.swing.JFormattedTextField();
        back_button = new javax.swing.JButton();
        register_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        set_name = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        create_account_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        create_account_label.setText("Create Account");

        set_emailid_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        set_emailid_label.setText("Email ID");

        set_username_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        set_username_label.setText("Username");

        set_password_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        set_password_label.setText("Password");

        set_phone_number_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        set_phone_number_label.setText("Phone Number");

        set_username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_username_fieldActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        register_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        register_button.setText("Register");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(create_account_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(set_emailid_label)
                                .addComponent(set_username_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(set_password_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(set_phone_number_label)
                            .addComponent(jLabel1))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(set_emailid_field, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(set_username_field)
                            .addComponent(set_password_field)
                            .addComponent(set_phone_number_field)
                            .addComponent(set_name, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(register_button)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(create_account_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(set_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set_emailid_label)
                    .addComponent(set_emailid_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set_username_label)
                    .addComponent(set_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set_password_label)
                    .addComponent(set_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set_phone_number_label)
                    .addComponent(set_phone_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button)
                    .addComponent(register_button))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void set_username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set_username_fieldActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login_page = new Login();
        login_page.setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        if (set_emailid_field.getText().equals("") || set_username_field.getText().equals("") || set_password_field.getPassword().equals("") || set_phone_number_field.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter valid credentials");
        }
        else {
            
            String name = set_name.getText();
            String phone_number = set_phone_number_field.getText();
            String email_id = set_emailid_field.getText();
            String user_name =  set_username_field.getText();
            String password = set_password_field.getText();
            int balance = 0,p=0;  
            
            
            //accessing user database
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myConnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user?characterEncoding=latin1","root","root");
                Statement mySttmt = myConnn.createStatement();
                ResultSet mytRs = mySttmt.executeQuery("select * from userdata where id= '"+user_name+"'" );
                if(mytRs.next())
                {
                    JOptionPane.showMessageDialog(null,"User id is already taken, try again");
                }
                else
                {
                    //checking whether it's a valid email address
                    for(int i=0;i<name.length();i++)
                    {
                        if(name.charAt(i)<='z' && name.charAt(i)>='a')
                        {
                            ;
                        }
                        else if(name.charAt(i)<='Z' && name.charAt(i)>='A' )
                        {
                            ;
                        }
                        else if(name.charAt(i)!=' ')
                        {
                            JOptionPane.showMessageDialog(null,"Please enter a valid name");
                            p=1;
                            break;
                        }
                    }              
                    if(p==0)
                    {
                        int counter = 0;
                        for(int i = 0; i<email_id.length();i++){
                            if(email_id.charAt(i) == '@' && counter == 0){
                                counter = 1;
                            }
                            if(email_id.charAt(i) == '.' && counter == 1){
                                counter = 2;
                            }
                        }
                        if(counter != 2){
                            JOptionPane.showMessageDialog(null,"Please enter a valid email address");
                        }

                        //check for 10 digit phone number 
                        int counter2 = 0;
                        if(phone_number.length() == 10){

                            counter2 = 1;
                            for(int i = 0; i<phone_number.length();i++){
                                if(phone_number.charAt(i)<'0' || phone_number.charAt(i)>'9')
                                {
                                    counter2=0;
                                }
                            }

                        }
                           if(counter2==0 && counter==2)
                           {
                               JOptionPane.showMessageDialog(null,"Please enter a valid phone number");
                           }

                        //sql queries
                        if(counter == 2 && counter2 == 1){
                            try{
            //                    Class.forName("com.mysql.jdbc.Driver"); 

                                Class.forName("com.mysql.jdbc.Driver");
                                Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user?characterEncoding=latin1","root","root");

                                String query = " insert into userdata (name, id, phone, email, password, balance , logged_in)"+ " values (?, ?, ?, ?, ?, ?, 0)";

                                PreparedStatement myStmt = myConn.prepareStatement(query);

                                myStmt.setString(1,name);
                                myStmt.setString(2,user_name);
                                myStmt.setString(3,phone_number);
                                myStmt.setString(4,email_id);
                                myStmt.setString(5,password);
                                myStmt.setInt(6,balance);

                                myStmt.execute();
            //                    ResultSet myRs = myStmt.executeQuery("select * from learner");
                    //            ResultSet myRs1 = myStmt.executeQuery("insert into learner values(2,002,'Gaurang Gupta')");


            //                    while(myRs.next()){
            //                        System.out.println(myRs.getString("name"));
            //                    }
                                myConn.close();
                                dispose();
                                Login login_page = new Login();
                                login_page.setVisible(true);
                            }
                            catch(Exception e){
                                System.out.println(e);
                            }
                        }
                    }
                }
                
                //creating user table in history database
                Class.forName("com.mysql.jdbc.Driver");
                Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/history?characterEncoding=latin1","root","root");
                Statement myStmt1 = myConn.createStatement();
                myStmt1.executeUpdate("create table "+ user_name +"(pickup varchar(25), dropoff varchar(25), fare int)");
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
       }            // TODO add your handling code here:
    }//GEN-LAST:event_register_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel create_account_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton register_button;
    private javax.swing.JFormattedTextField set_emailid_field;
    private javax.swing.JLabel set_emailid_label;
    private javax.swing.JFormattedTextField set_name;
    private javax.swing.JPasswordField set_password_field;
    private javax.swing.JLabel set_password_label;
    private javax.swing.JFormattedTextField set_phone_number_field;
    private javax.swing.JLabel set_phone_number_label;
    private javax.swing.JTextField set_username_field;
    private javax.swing.JLabel set_username_label;
    // End of variables declaration//GEN-END:variables
}
