
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
    public class DriverPage extends javax.swing.JFrame {
    String user_id, pickup_g, drop_g, driver_name_g;
    int fare_g,dur_g;
    float driver_rating_g;
    Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Rohan\\Documents\\NetBeansProjects\\OOP_Project\\bg1.jpg");
    /**
     * Creates new form DriverPage
     */
    public DriverPage(String user_id, String pickup, String drop, int fare, String driver_name, float driver_rating) {

        setResizable(false);
        this.setContentPane(new JPanel()
                {
                    @Override
                    public void paintComponent(Graphics g)
                {
                    super.paintComponent(g);
                    g.drawImage(img, 0, 0, 800, 680, this);
                }
                });
        setResizable(false);
       
        initComponents();
        this.user_id = user_id;
        user_msg.setText("You are logged in as " + user_id);
        System.out.println("\n" + user_id + "\n");
        final_fare_val.setFont(new java.awt.Font("Dialog", 1, 24));
        final_fare_val.setText("" + fare + "");
        fare_g = fare;
        dur_g=fare/10;
        pick_loc_val.setFont(new java.awt.Font("Dialog", 1, 24));
        pick_loc_val.setText(pickup);
        pickup_g = pickup;
        
        drop_loc_val.setFont(new java.awt.Font("Dialog", 1, 24));
        drop_loc_val.setText(drop);
        drop_g = drop;
        
        dri_name_val.setFont(new java.awt.Font("Dialog", 1, 24));
        dri_name_val.setText(driver_name);
        driver_name_g = driver_name;
        
        dri_rating_val.setFont(new java.awt.Font("Dialog", 1, 24));
        dri_rating_val.setText(String.valueOf(driver_rating));
        driver_rating_g = driver_rating;
        String carno="",carty="";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers?characterEncoding=latin1","root","root");
            
            //updating driver status -dev
            Statement myStmt2 = myConnn.createStatement();
            myStmt2.executeUpdate("update driver set cur_status = 1 where driver_name = '" + driver_name_g + "'");
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers?characterEncoding=latin1","root","root");
            Statement myStmt = myConn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from driver where driver_name ='"+driver_name+"'");
            while(myRs.next())
            {
                carno=myRs.getString("car");
                carty=myRs.getString("car_number");
            }
            car_no.setFont(new java.awt.Font("Dialog", 1, 24));   // Add car number here
            car_no.setText(String.valueOf(carno));
            //car_no = driver_rating;

            car_type.setFont(new java.awt.Font("Dialog", 1, 24));   // Add car here
            car_type.setText(String.valueOf(carty));
            //car_type = driver_rating;

            duration.setFont(new java.awt.Font("Dialog", 1, 24));   // Add duration here
            duration.setText(String.valueOf(dur_g)+"sec");
            //duration = driver_rating;
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dri_name = new javax.swing.JLabel();
        dri_rating = new javax.swing.JLabel();
        pick_loc = new javax.swing.JLabel();
        drop_loc = new javax.swing.JLabel();
        coupon_code = new javax.swing.JLabel();
        verify_code = new javax.swing.JButton();
        final_fare = new javax.swing.JLabel();
        confirm_booking = new javax.swing.JButton();
        final_fare_val = new javax.swing.JLabel();
        pick_loc_val = new javax.swing.JLabel();
        drop_loc_val = new javax.swing.JLabel();
        dri_name_val = new javax.swing.JLabel();
        dri_rating_val = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coupon_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        car_type = new javax.swing.JLabel();
        car_no = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        user_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Driver Details");

        dri_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dri_name.setText("Driver Name:");

        dri_rating.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dri_rating.setText("Driver Rating:");

        pick_loc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pick_loc.setText("Pick-Up Location:");

        drop_loc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drop_loc.setText("Drop Location:");

        coupon_code.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        coupon_code.setText("Coupon Code:");

        verify_code.setText("Verify & Apply Code");
        verify_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_codeActionPerformed(evt);
            }
        });

        final_fare.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        final_fare.setText("Final Fare:");

        confirm_booking.setText("Confirm Booking");
        confirm_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_bookingActionPerformed(evt);
            }
        });

        coupon_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coupon_inputActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Car: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Duration:");

        user_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(user_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(250, 250, 250))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pick_loc)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(final_fare_val, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon_input, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(final_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(confirm_booking)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drop_loc)
                                    .addComponent(dri_name, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dri_rating, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dri_rating_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dri_name_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drop_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pick_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(car_type, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(car_no, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coupon_code)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verify_code)))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pick_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pick_loc))
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(drop_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drop_loc))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dri_name)
                            .addComponent(dri_name_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dri_rating)
                            .addComponent(dri_rating_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addComponent(car_type, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car_no, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coupon_input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verify_code)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coupon_code)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(final_fare_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(final_fare))
                        .addGap(17, 17, 17)))
                .addComponent(jLabel14)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_booking)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_bookingActionPerformed
        // TODO add your handling code here:
   
        // Gaurang is adding the drivers ka refreshing algo here. So contact him for any problems;
        int tot_trips=0;
	try
	{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers?characterEncoding=latin1","root","root");
            
                        //updating driver number of trips -dev
            Statement myStmt3 = myConn.createStatement();
            ResultSet myRs3 = myStmt3.executeQuery("select * from driver where driver_name = '" + driver_name_g + "'");
            int a = 0;
            while(myRs3.next()){
                a = myRs3.getInt("num_trips") + 1;
            }
            Statement myStmt4 = myConn.createStatement();
            myStmt4.executeUpdate("update driver set num_trips = " + a + " where driver_name = '" + driver_name_g + "'");
            
            
            
            //updating driver location based on total number of trips 
            Statement myStmt = myConn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from driver");
            while(myRs.next())
            {
		tot_trips+=myRs.getInt("num_trips");
            }
            
            tot_trips-=150;
            if(tot_trips%5==0)
            {
            	String upda="Update driver set cur_pos = initial_pos where cur_status = 0 ";
            	myStmt.executeUpdate(upda);
            }
	}
        catch(Exception e)
	{
            e.printStackTrace();
            System.out.println(e);
	}
        System.out.println("Reached the end");
        
        dispose();
        TravelPage tp = new TravelPage(user_id, pickup_g,drop_g,driver_name_g,dur_g,fare_g);
        tp.setVisible(true);
        
    }//GEN-LAST:event_confirm_bookingActionPerformed

    private void coupon_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coupon_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coupon_inputActionPerformed

    private void verify_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_codeActionPerformed
        // TODO add your handling code here:
        String a = coupon_input.getText();
        //JOptionPane.showMessageDialog (null,a);
        //String flag = "";
        int fare_temp = fare_g;
        //JOptionPane.showMessageDialog (null,String.valueOf(fare));
//the value of fare is being picked from the constructor method
        
        try
        {
            int p=0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coupon?characterEncoding=latin1","root","root");
            Statement myStmt = myConn.createStatement();
            ResultSet myRss = myStmt.executeQuery("select * from coup_details" );
            while(myRss.next())
            {
                if(myRss.getString("code").equals(a))
                {
                    p++;
                    double discount = myRss.getInt("value")/100.0;
                    //JOptionPane.showMessageDialog (null,String.valueOf(discount));
                    fare_temp = (int) (fare_temp * (1 - discount));
                    //JOptionPane.showMessageDialog (null,String.valueOf(fare));
                    final_fare_val.setFont(new java.awt.Font("Dialog", 1, 24));
                    final_fare_val.setText("" + String.valueOf(fare_temp) + "");
                    fare_g=fare_temp;
                    verify_code.setEnabled(false);
                }
            }
            if(p==0)
            {
                JOptionPane.showMessageDialog(null,"The given coupon does not exist");
            }
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_verify_codeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
                Connection myConnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers?characterEncoding=latin1","root","root");

                //updating driver status -dev
                Statement myStmt2 = myConnn.createStatement();
                myStmt2.executeUpdate("update driver set cur_status = 0 where driver_name = '" + driver_name_g + "'");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        dispose();
        BookingScreen bk = new BookingScreen(user_id);
        bk.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DriverPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel car_no;
    private javax.swing.JLabel car_type;
    private javax.swing.JButton confirm_booking;
    private javax.swing.JLabel coupon_code;
    private javax.swing.JTextField coupon_input;
    private javax.swing.JLabel dri_name;
    private javax.swing.JLabel dri_name_val;
    private javax.swing.JLabel dri_rating;
    private javax.swing.JLabel dri_rating_val;
    private javax.swing.JLabel drop_loc;
    private javax.swing.JLabel drop_loc_val;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel final_fare;
    private javax.swing.JLabel final_fare_val;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel pick_loc;
    private javax.swing.JLabel pick_loc_val;
    private javax.swing.JLabel user_msg;
    private javax.swing.JButton verify_code;
    // End of variables declaration//GEN-END:variables
}
