import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.WindowConstants;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Rohan\\Documents\\NetBeansProjects\\OOP_Project\\logo.jpg");
//    Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\user\\Desktop\\OOP_Project\\logo.jpg");
    
    public Login() {
        this.setContentPane(new JPanel()
                {
                    @Override
                    public void paintComponent(Graphics g)
                {
                    super.paintComponent(g);
                    g.drawImage(img, 0, 0, 700, 560, this);
                }
                });
        setResizable(false);
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_title_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        create_account_button = new javax.swing.JButton();
        forgot_pass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        login_title_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login_title_label.setText("Login Page");

        username_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        username_label.setText("Username");

        password_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        password_label.setText("Password");

        username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textfieldActionPerformed(evt);
            }
        });

        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        exit_button.setText("Exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        create_account_button.setText("Create Account");
        create_account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_account_buttonActionPerformed(evt);
            }
        });

        forgot_pass.setText("Forgot Password");
        forgot_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_label)
                    .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_field, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(username_textfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(forgot_pass)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(create_account_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_title_label))
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(login_title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgot_pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(create_account_button)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_button)
                    .addComponent(exit_button)
                    .addComponent(login_button))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textfieldActionPerformed

    private void create_account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_account_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        CreateAccount create_account = new CreateAccount();
        create_account.setVisible(true);
    }//GEN-LAST:event_create_account_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
        password_field.setText(null);
        username_textfield.setText(null);
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        if (password_field.getText().equals("") || username_textfield.getText().equals(""))
		{
            JOptionPane.showMessageDialog(null,"Username and Password field cannot be empty");
        }
        else 
		{
			int p=0, q = 0;
            String tpass = password_field.getText();
            String tname = username_textfield.getText();
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user?characterEncoding=latin1","root","root");
            Statement myStmt = myConn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from userdata");
            int balance = 0;
            while(myRs.next())
                {
                    if(myRs.getString("id").equals(tname))
                    {
                            if(myRs.getString("password").equals(tpass))
                            {
                                    Statement mySttmt = myConn.createStatement();
                                    ResultSet myRss = mySttmt.executeQuery("select * from userdata where id = '"+tname+"'");
                                    while(myRss.next())
                                    {
                                        p=myRss.getInt("logged_in");
                                    }
                                    if(p==1)
                                    {
                                        JOptionPane.showMessageDialog(null,"User is already logged in");
                                    }
                                    else
                                    {
                                        try
                                        {
                                            Class.forName("com.mysql.jdbc.Driver");
                                            Connection myConnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user?characterEncoding=latin1","root","root");
                                            Statement myStmmt = myConnn.createStatement();
                                            myStmmt.executeUpdate("update userdata set logged_in = 1 where id = '" + tname + "'");
                                        }
                                        catch(Exception e)
                                        {
                                           System.out.println(e);
                                        }
                                        balance = myRs.getInt("balance");
                                        p=1;
                                        JOptionPane.showMessageDialog(null,"Successfully logged in as "+ tname, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                        dispose();
                                        MainFrame main_fr = new MainFrame(tname, balance);
                                        main_fr.setVisible(true);
                                    }
                            }
                            else
                            {
                                    JOptionPane.showMessageDialog(null,"Username and Password do not match");
                                    q = 1;
                            }
                    }
                }
                if(p == 0 && q == 0)
                {
                        JOptionPane.showMessageDialog(null,"There is no such user");
                }
            }
            catch(Exception e){
                System.out.println(e);
            }
           }
            
    }//GEN-LAST:event_login_buttonActionPerformed

     
    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed
    
    private void forgot_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_passActionPerformed
        // TODO add your handling code here:
        dispose();
        ChangePassword cp = new ChangePassword();
        cp.setVisible(true);
        
    }//GEN-LAST:event_forgot_passActionPerformed

    
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        //trying to run the refreshing algorithm from main
//        int tot_trips = 0;
//        
//        try{
//        Class.forName("com.mysql.jdbc.Driver");
//        Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers","root","root");
//        Statement myStmt = myConn.createStatement();
//        String update = "Update driver set cur_pos = initial_pos where cur_status = 0 ";
//        while(true){
//        
//            //            //updating driver location based on total number of trips 
//            
////            ResultSet myRs = myStmt.executeQuery("select * from driver");
////            while(myRs.next())
////            {
////		tot_trips+=myRs.getInt("num_trips");
////            }
////            
////            tot_trips-=150;
////            if(tot_trips%5==0)
////            {
////            	String upda="Update driver set cur_pos = initial_pos where cur_status = 0 ";
////            	myStmt.executeUpdate(upda);
////            }
//            
//            
//            myStmt.executeUpdate(update);
////            Thread.sleep(10000);
//        
//        
//        }
//        }
//        catch(Exception e){
//            e.printStackTrace();
//        }



        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_account_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton forgot_pass;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel login_title_label;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton reset_button;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
